version: '3.8'

services:
  zipkin:
    image: 'openzipkin/zipkin'
    ports:
      - '9411:9411'

  prometheus:
    image: 'prom/prometheus'
    ports:
      - '9090:9090'
    network_mode: "host"
    command: --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./scripts/prometheus.yml:/etc/prometheus/prometheus.yml

